# Generated by Django 3.2.1 on 2021-05-08 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='List',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=160)),
                ('deadline', models.DateField(blank=True, null=True)),
                ('percent', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
